# Site settings
title: P2P Markets
email: mb389@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Insights into Peer to Peer Loan Investment Strategy
baseurl: "/p2p" # the subpath of your site, e.g. /blog/
url: "https://mb389.github.io" # the base hostname & protocol for your site
twitter_username: mb389
github_username:  mb389

# Build settings
markdown: kramdown
